name: PR CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'src/**.json'
      - 'src/**.png'

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Dependency Review
        uses: actions/dependency-review-action@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build and Test
        uses: gradle/gradle-command-action@v2
        with:
          arguments: |
            checkLicenses
            buildSrc:checkLicenses
            build
            test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
